version: "3.8"

services:
  postgres:
    build:
      context: ./Docker
      dockerfile: Dockerfile_postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=default
    #user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - docker_network

  nipohc_app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile_fastapi
    container_name: nipohc_app
    image: nipohc_app_image
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "nipohc_user"
      POSTGRES_DB: "nipohc"
      POSTGRES_HOST: "postgres"
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8000"
    ports:
      - "8000:80"
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
    name: docker_network
